spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        native:
          #search-location: "classpath:/config"
          #search-location: "file:///Users/smajumder02/Documents/config/"
        git:
          uri: "https://github.com/SambitMajumder/eazybytes-config-main.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "36818793i1g3u1vue281yei21y89e"


server:
  port: 8071
